# Generated by Django 5.1.6 on 2025-03-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventTitle', models.CharField(max_length=200)),
                ('EventRank', models.IntegerField(default=-1)),
                ('EventDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListName', models.CharField(max_length=200)),
                ('Events', models.ManyToManyField(to='hello_world_app.todoevent')),
            ],
        ),
    ]
