# Generated by Django 5.1.6 on 2025-03-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0003_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoevent',
            old_name='author',
            new_name='owner',
        ),
    ]
