# Generated by Django 5.1.6 on 2025-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0004_rename_author_todoevent_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoevent',
            name='EventDescription',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='todoevent',
            name='EventRank',
            field=models.IntegerField(default=1),
        ),
    ]
