# Generated by Django 5.1.6 on 2025-03-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0005_todoevent_eventdescription_alter_todoevent_eventrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoevent',
            name='EventList',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
