# Generated by Django 5.1.6 on 2025-03-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0006_todoevent_eventlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoevent',
            name='EventDescription',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
