# Generated by Django 5.1.6 on 2025-03-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0007_alter_todoevent_eventdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoevent',
            name='EventRank',
        ),
    ]
