# Generated by Django 5.1.6 on 2025-03-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0008_remove_todoevent_eventrank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
